// frontend-nextjs/app/page.tsx
'use client';
import { useState } from 'react';


const API_BASE = process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:5000';


export default function LoginPage() {
  const [phone, setPhone] = useState('');
  const [otp, setOtp] = useState('');
  const [error, setError] = useState<string | null>(null);

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    try {
      const res = await fetch(`${API_BASE}/auth/verify-otp`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ phone, otp }),
      });
      if (!res.ok) {
        setError('OTP inválido');
        return;
      }
      window.location.href = '/home';
    } catch {
      setError('Network error');
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black" style={{ backgroundColor: '#F0F9FF' }}>
      <div style={{
        backgroundColor: 'rgba(255,255,255,0.75)',
        border: '1px solid rgba(229,231,235,0.6)',
        borderRadius: 16,
        backdropFilter: 'blur(8px)',
        boxShadow: '0 10px 25px rgba(0,0,0,0.15)',
        padding: 24,
        width: '100%',
        maxWidth: 520,
        margin: '0 auto',
        color: '#000000'
      }}>
        <h1 style={{ marginTop: 0, marginBottom: 8, fontSize: 20, color: '#111827' }}>Welcome to the app (Next.js)</h1>
        <p style={{ color: '#111827', marginBottom: 12 }}>Use OTP 123456.</p>
        <form onSubmit={onSubmit} style={{ display: 'grid', gap: 10 }}>
          <div>
            <label style={{ color: '#374151' }}>Phone</label>
            <input className="block w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              value={phone} onChange={(e) => setPhone(e.target.value)} required style={{ display: 'block', width: '100%', marginTop: 4 }} />
          </div>
          <div>
            <label style={{ color: '#374151' }}>OTP</label>
            <input className="block w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              value={otp} onChange={(e) => setOtp(e.target.value)} required style={{ display: 'block', width: '100%', marginTop: 4 }} />
          </div>
          <button type="submit" style={{
            backgroundColor: '#0C4A6E', color: 'white', border: 'none',
            padding: '10px 16px', borderRadius: 8, cursor: 'pointer',
            width: 'fit-content'
          }}>Sign in</button>
        </form>
        {error && <p style={{ color: '#DC2626', marginTop: 8 }}>{error}</p>}
      </div>
    </div>
  );
}

// frontend-angular2/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'Angular Admin';
  apiBase = 'http://localhost:5000';

  email = '';
  password = '';
  error: string | null = null;
  adminName: string | null = null;
  view: 'login' | 'dashboard' = 'login';

  constructor(private http: HttpClient) { }

  async login(e: Event) {
    e.preventDefault();
    this.error = null;
    try {
      await this.http.post(
        `${this.apiBase}/auth/login-admin`,
        { email: this.email, password: this.password },
        { withCredentials: true }
      ).toPromise();
      // Fetch me
      const me: any = await this.http.get(`${this.apiBase}/session/me`, { withCredentials: true }).toPromise();
      this.adminName = me?.adminName ?? 'Administrador';
      this.view = 'dashboard';
    } catch {
      this.error = 'Credenciales inválidas';
    }
  }

  openUserApp() {
    window.location.href = 'http://localhost:4201';
  }

  async logout() {
    await this.http.post(`${this.apiBase}/auth/logout`, {}, { withCredentials: true }).toPromise();
    this.view = 'login';
    this.email = '';
    this.password = '';
  }
}

<div *ngIf="view === 'dashboard'"
  style="background-color:#FEF3C7; color:#92400E; padding:12px 16px; display:flex; justify-content:space-between; align-items:center; font-family: Arial, Helvetica, sans-serif">
  <span style="font-weight:600">Angular Admin</span>
  <button (click)="logout()"
    style="background-color:#92400E; color:white; border:none; padding:8px 12px; border-radius:6px; cursor:pointer">Logout</button>
</div>

<div
  style="min-height: calc(100vh - 56px); display: flex; align-items: center; justify-content: center; padding: 24px; font-family: Arial, Helvetica, sans-serif; background-color: #F9FAFB;">
  <div
    style="width: 100%; max-width: 520px; background: #FFFFFF; border: 1px solid #E5E7EB; border-radius: 12px; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1); padding: 24px;">
    <h1 style="margin-top: 0; margin-bottom: 16px; font-size: 20px; color: #111827;">{{ title }}</h1>
    <div *ngIf="view === 'login'; else dashboard">
      <form (submit)="login($event)" style="display: grid; gap: 10px;">
        <label style="color:#374151">Email</label>
        <input [(ngModel)]="email" name="email" required
          style="padding:8px 10px; border:1px solid #D1D5DB; border-radius:8px;" />
        <label style="color:#374151">Password</label>
        <input [(ngModel)]="password" name="password" type="password" required
          style="padding:8px 10px; border:1px solid #D1D5DB; border-radius:8px;" />
        <small style="color:#6B7280">Hardcoded credentials: admin&#64;example.com / password123</small>
        <button type="submit"
          style="background-color:#0C4A6E; color:white; border:none; padding:10px 16px; border-radius:8px; cursor:pointer">Ingresar</button>
      </form>
      <p *ngIf="error" style="color: #DC2626; margin-top:8px;">{{ error }}</p>
    </div>
    <ng-template #dashboard>
      <p style="margin-top:0; color:#111827">Welcome, {{ adminName }}</p>
      <h3 style="margin-bottom: 12px; color:#111827">User applications</h3>
      <div style="display:grid; gap: 10px;">
        <button (click)="openUserApp()"
          style="text-align:center; background-color:#5B21B6; color:white; border:none; padding:10px 16px; border-radius:8px; cursor:pointer">Application
          #1 (Angular User)</button>
        <button (click)="openNextApp()"
          style="text-align:center; background-color:#0C4A6E; color:white; border:none; padding:10px 16px; border-radius:8px; cursor:pointer">Application
          #2 (Next.js Dashboard)</button>
      </div>
    </ng-template>
  </div>
</div>
<router-outlet></router-outlet>
